name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set-up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Inject API key
      id: custom
      shell: sh
      run: |
        sed -i 's/__API_KEY_GOES_HERE__/${{ secrets.REDDIT_API_KEY }}/' app/src/main/java/ml/docilealligator/infinityforreddit/utils/APIUtils.java
        echo "app_version=$(grep -m 1 versionName app/build.gradle | cut -d '"' -f 2)" >>"$GITHUB_OUTPUT"

    - name: Setup and build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleRelease

    - name: Send apk
      uses: dawidd6/action-send-mail@v5
      with:
        server_address: smtp.mailgun.org
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        to: ${{ secrets.TO_EMAIL }}
        from: asardaes <${{ secrets.FROM_EMAIL }}>
        subject: Reddit Infinity APK
        body: APK for version ${{ steps.custom.outputs.app_version }}
        attachments: app/build/outputs/apk/release/app-release.apk
